repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.4.0
        hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-added-large-files

    -   repo: https://github.com/psf/black
        rev: 23.3.0
        hooks:
        -   id: black

    -   repo: https://github.com/charliermarsh/ruff-pre-commit
        rev: v0.0.267
        hooks:
            -   id: ruff

    -   repo: https://github.com/pycqa/pylint
        rev: v3.0.0a6
        hooks:
        -   id: pylint
            files: "src/"

    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: v1.1.1
        hooks:
        -   id: mypy
            files: "src/"
            args: [--strict, --no-incremental]

    -   repo: https://github.com/regebro/pyroma
        rev: "4.2"
        hooks:
        -   id: pyroma
